default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: study_assistant_development

test:
  <<: *default
  database: study_assistant_test

production:
  <<: *default
  database: study_assistant_production
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
