default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>  # 默认连接本地主机，可通过环境变量覆盖
  username: <%= ENV['POSTGRES_USERNAME'] %>         # 从环境变量读取用户名
  password: <%= ENV['POSTGRES_PASSWORD'] %>         # 从环境变量读取密码

development:
  <<: *default
  database: study_assistant_development               # 开发环境数据库名称

test:
  <<: *default
  database: study_assistant_test                      # 测试环境数据库名称

production:
  <<: *default
  database: study_assistant_production                # 生产环境数据库名称
  username: <%= ENV['POSTGRES_USERNAME'] %>           # 必须通过环境变量提供用户名
  password: <%= ENV['POSTGRES_PASSWORD'] %>           # 必须通过环境变量提供密码
  host: <%= ENV['POSTGRES_HOST'] %>                   # 必须通过环境变量提供远程主机地址
