name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        if [ -z "$DEPLOY_HOST" ]; then
          echo "DEPLOY_HOST is not set. Please check your environment variables."
          exit 1
        fi
        ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
        echo "SSH setup complete. Known hosts:"
        cat ~/.ssh/known_hosts

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST echo "Connection successful"

    - name: Deploy code
      run: |
        ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST <<EOF
        set -e
        echo "Starting deployment"
        cd ~/Study-Assistant
        git pull origin main
        bundle install --deployment --without development test
        RAILS_ENV=production rails db:migrate
        RAILS_ENV=production rails assets:precompile
        sudo systemctl restart puma
        sudo systemctl restart nginx
        echo "Deployment complete"
        EOF
