name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          echo "SSH setup complete. Known hosts:"
          cat ~/.ssh/known_hosts

      - name: Debug environment variables
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          echo "DEPLOY_HOST=$DEPLOY_HOST"
          echo "DEPLOY_USER=$DEPLOY_USER"

      - name: Deploy application
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          echo "Starting deployment to $DEPLOY_HOST..."
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST <<EOF
          echo "Connected to server"
          cd /home/$DEPLOY_USER/Study-Assistant
          git pull origin main
          RAILS_ENV=production bundle install
          RAILS_ENV=production rails db:migrate
          RAILS_ENV=production rails assets:precompile
          sudo systemctl restart nginx
          pkill -f puma
          RAILS_ENV=production bundle exec puma -C config/puma.rb &
          echo "Deployment complete!"
          EOF
